name             'chef-servicesAttributes'
maintainer       'PE, pf.'
maintainer_email 'peychart@mail.pf'
license          'GNU Public License 3.0'
description      'Installs/Configures chef-servicesAttributes'
long_description 'Installs/Configures chef-servicesAttributes'
version          '0.1.0'
